name: OPA Service CI/CD

on:
  push:
    paths:
      - 'opa-service/**'
    branches:
      - 'infra'

jobs:
  build-and-deploy-opa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        cd opa-service
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/foliage:${{ github.sha }} .

    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/foliage:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy opa-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/foliage:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated